# Define the objects to be evualated against defined rules

objects:
  shapes:
    - colour: [red, green]
      shape: rectangle
      size: large

    - colour: green
      shape: circle
      size: small

  cars:
    - colour: grey
      size: small
      doors: 3

    - colour: black
      size: large
      doors: 5
