# Objects to be evualated against defined rules

config:
  # define whether to use defined objects or generate them randomly
  - use_defined_objects: true

objects:
  - colour: [red, green]
    shape: rectangle
    size: large

  - colour: green
    shape: circle
    size: small
